#!/bin/sh

AVAILABLE_VARS=('river-touchpad-id' 'bt-headset-dev')
ENV_DIR=~/.config/environment.d

var_name() {
  echo $1 | tr '[:lower:]-' '[:upper:]_'
}

env_file_path() {
  echo $1 \
    | tr '[:upper:]_' '[:lower:]-' \
    | xargs printf '%s/50-%s.conf' "$ENV_DIR"
}

setvar() {
  env_str="$(var_name "$1")=$2"
  systemctl --user set-environment "$env_str"

  # persist
  mkdir -p "$ENV_DIR"
  echo "$env_str -> $(env_file_path "$1")"
  echo "$env_str" > "$(env_file_path "$1")"
  systemctl --user daemon-reload
}

getvar() {
  systemctl --user show-environment \
    | grep -Po "(?<=^$(var_name "$1")=).*"
}

comps() {
  case "$1" in
    'bt-headset-dev')
      LC_ALL=C bluetoothctl devices | sed 's/^Device //'
      ;;
    'river-touchpad-id')
      LC_ALL=C riverctl list-inputs | grep -v '^$' | grep -v '^\s'
      ;;
  esac
}

case "$1" in
  '')
    for var in ${AVAILABLE_VARS[@]}; do
      printf "%s: %s\n" "$var" "$(getvar "${var}" || echo "(not set)")"
      comps "${var}" | sed 's/^/    /'
    done
    ;;
  'help')
    echo "usage: $0 [help | <var> [<value>]]"
    ;;
  *)
    if [[ '' != "$2" ]]; then
      setvar "$1" "$2"
    else
      getvar "$1"
    fi
    ;;
esac
