#!/bin/sh

# (river 0.3.5)
# `wlrctl` looks interesting.

WIN95_BG_COLOR=0x008080 # or 0x007e7d?
RED=0xff0000
LIME=0x00ff00
GREY=0x202020
BLACK=0x000000

riverctl background-color       $BLACK
riverctl border-color-focused   $RED
riverctl border-color-unfocused $GRAY
border-color-urgent             $RED
border-width pixels             1

# keyboard settings
riverctl set-repeat 50 300


## Input Devices ######################################################

# type-numerical_vendor_id-numerical_product_id-self_advertised_name
# see: riverctl list-inputs
FW_TOUCHPAD="pointer-2362-628-PIXA3854:00_093A:0274_Touchpad"

# Generally 'none' means 'default'
#
# Note: scrolling in FF can be fixed by "mousewheel.default.delta_multiplier_y"
#
# See:
# - https://wayland.freedesktop.org/libinput/doc/latest/configuration.html
# - https://wayland.freedesktop.org/libinput/doc/latest/api/group__config.html
# - man riverctl
# - libinput list-devices
# - riverctl list-inputs
#
# Issues:
# - kinetic scrolling won't stop on tap or key press (likely Firefox bug)
# - drag-lock locks taps even in context menus, confirming selection
# - wish I could have 3-finger drag

riverctl input "$FW_TOUCHPAD" accel-profile          adaptive    # none|flat|adaptive
riverctl input "$FW_TOUCHPAD" pointer-accel          0.0         # -1.0..1.0
riverctl input "$FW_TOUCHPAD" click-method           clickfinger # none|button-areas|clickfinger
riverctl input "$FW_TOUCHPAD" drag                   enabled     # (wish I could have 3-finger drag)
riverctl input "$FW_TOUCHPAD" drag-lock              disabled
riverctl input "$FW_TOUCHPAD" disable-while-typing   enabled
riverctl input "$FW_TOUCHPAD" natural-scroll         enabled
riverctl input "$FW_TOUCHPAD" scroll-factor          1
riverctl input "$FW_TOUCHPAD" tap                    enabled
riverctl input "$FW_TOUCHPAD" tap-button-map         left-right-middle
riverctl input "$FW_TOUCHPAD" scroll-method          two-finger


## Rules ##############################################################

# Easiest way to find `-title` and `-app-id`: [lswt](https://git.sr.ht/~leon_plickat/lswt)

riverctl rule-add -app-id firefox ssd # make the focused border visible


## Bindings ###########################################################

# bindings - general
riverctl map normal Super+Shift Q exit

# bindings - apps
riverctl map normal Super+Shift Return spawn foot
riverctl map normal Super+Shift F spawn firefox
riverctl map normal Super+Shift Y spawn 'wl-paste | xargs yt-dlp -o - | mpv -'

# bindings - special
riverctl map normal Super+Shift B spawn 'bluetoothctl connect 57:84:82:33:C4:2B'

# bindings - top row
for mode in normal locked
do
    riverctl map $mode None XF86AudioMute                 spawn 'wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle'
    riverctl map -repeat $mode None XF86AudioLowerVolume  spawn 'wpctl set-volume @DEFAULT_AUDIO_SINK@ 1%-'
    riverctl map -repeat $mode None XF86AudioRaiseVolume  spawn 'wpctl set-volume @DEFAULT_AUDIO_SINK@ 1%+'
    # TODO riverctl map $mode None XF86AudioPrev  spawn 'playerctl previous'
    # TODO riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
    # TODO riverctl map $mode None XF86AudioPlay  spawn 'playerctl play-pause'
    # TODO riverctl map $mode None XF86AudioNext  spawn 'playerctl next'
    riverctl map -repeat $mode None XF86MonBrightnessDown spawn 'brightnessctl set 1%-'
    riverctl map -repeat $mode None XF86MonBrightnessUp   spawn 'brightnessctl set +1%'
    # TODO some kind of screen button?
    # TODO XF86WWAN or XF86RFKill
    # TODO PrintScreen
    # TODO Seems like settings, or Framework logo?
done

# bindings - views
riverctl map normal Super+Shift C        close
riverctl map normal Super Return         zoom
riverctl map normal Super S              toggle-float
riverctl map normal Super F              toggle-fullscreen

# focus with Super+[direction]
riverctl map normal Super H              focus-view left
riverctl map normal Super J              focus-view down
riverctl map normal Super K              focus-view up
riverctl map normal Super L              focus-view right
riverctl map normal Super N              focus-view next
riverctl map normal Super P              focus-view previous

# swap with Super+Shift+[direction]
riverctl map normal Super+Shift H        swap left
riverctl map normal Super+Shift J        swap down
riverctl map normal Super+Shift K        swap up
riverctl map normal Super+Shift L        swap right
riverctl map normal Super+Shift N        swap next
riverctl map normal Super+Shift P        swap previous

# floating windows management
# - move with Super+Alt+[dir]
# - snap with Super+Alt+Control+[dir]
# - resize with Super+Alt+Shift+[dir]
riverctl map normal Super+Alt H          move        left        100
riverctl map normal Super+Alt J          move        down        100
riverctl map normal Super+Alt K          move        up          100
riverctl map normal Super+Alt L          move        right       100
riverctl map normal Super+Alt+Control H  snap        left
riverctl map normal Super+Alt+Control J  snap        down
riverctl map normal Super+Alt+Control K  snap        up
riverctl map normal Super+Alt+Control L  snap        right
riverctl map normal Super+Alt+Shift H    resize      horizontal -100
riverctl map normal Super+Alt+Shift J    resize      vertical    100
riverctl map normal Super+Alt+Shift K    resize      vertical   -100
riverctl map normal Super+Alt+Shift L    resize      horizontal  100

# bindings - tags (TODO learning these still)
# TODO riverctl map normal Super bracketleft set-focused-tags -1
for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    # Super+[1-9] to focus tag [0-8]
    riverctl map normal Super $i set-focused-tags $tags

    # Super+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal Super+Shift $i set-view-tags $tags

    # Super+Control+[1-9] to toggle focus of tag [0-8]
    riverctl map normal Super+Control $i toggle-focused-tags $tags

    # Super+Shift+Control+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
done

# layout generator
pkill wideriver; wideriver \
    --layout wide \
    --ratio-wide .5 \
    --smart-gaps \
    --stack even \
    --count-wide-left 1 \
    --border-width 2 \
    --border-color-focused $RED \
    --border-color-unfocused $BLACK \
    &

riverctl default-layout wideriver

#riverctl default-layout rivertile
#rivertile -view-padding 0 -outer-padding 0 &

# startup
pkill kanshi ; kanshi &
pkill waybar ; waybar &
pkill mako ; mako &
